<?php
namespace Tools;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-09-30 at 22:12:01.
 */
class StringTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var String
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Tools\String::startWith
     * @todo   Implement testStartWith().
     */
    public function testStartWith()
    {
        $obj = new String("'__");
        $v = $obj->startWith("'");
        $this->assertTrue($v);

        $v = $obj->startWith("_",1);
        $this->assertTrue($v);

        $v = $obj->startWith("__",1);
        $this->assertTrue($v);
    }

    /**
     * @covers Tools\String::endWith
     * @todo   Implement testEndWith().
     */
    public function testEndWith()
    {
        $obj = new String("'__");
        $v = $obj->endWith("_");
        $this->assertTrue($v);

        $obj = new String("12345");
        $v = $obj->endWith("45");
        $this->assertTrue($v);
    }
}
